"""Immutable domain models for the SignRiver application module."""

from .games import (
    AdapterCapability,
    AdapterDescriptor,
    GameInstallation,
    GameState,
    InstallationCandidate,
    Metadata,
    PathInput,
    ValidationResult,
)
from .catalog import DlcCatalogEntry, NormalizedRelease, ReleaseAsset
from .downloads import DownloadSnapshot, DownloadSpec, DownloadState
from .installs import (
    DiskSpaceRequirement,
    InstallAudit,
    InstallHealth,
    InstallMaintenanceEntry,
    InstallMaintenancePreview,
    InstallMaintenanceResult,
    InstallPhase,
    InstallPlan,
    InstallReceipt,
    InstallSpaceEstimate,
    OwnedFile,
)
from .patches import (
    PatchAssetRole,
    PatchAudit,
    PatchBundle,
    PatchHealth,
    PatchProfile,
    PatchReceipt,
    PatchTemplate,
)
from .cartridges import (
    CARTRIDGE_DOCUMENT_SCHEMA,
    CARTRIDGE_INDEX_SCHEMA,
    HUB_RELEASE_TAG,
    INDEX_ASSET_NAME,
    CartridgeDocument,
    CartridgeIndex,
    CartridgeIndexEntry,
)
from .settings import UserSettings
from .paths import game_relative_path, normalize_game_relative_directory, resolve_game_directory

__all__ = [
    "AdapterCapability",
    "AdapterDescriptor",
    "GameInstallation",
    "GameState",
    "InstallationCandidate",
    "Metadata",
    "PathInput",
    "ValidationResult",
    "DlcCatalogEntry",
    "NormalizedRelease",
    "ReleaseAsset",
    "DownloadSnapshot",
    "DownloadSpec",
    "DownloadState",
    "InstallPhase",
    "InstallHealth",
    "InstallAudit",
    "DiskSpaceRequirement",
    "InstallSpaceEstimate",
    "InstallMaintenanceEntry",
    "InstallMaintenancePreview",
    "InstallMaintenanceResult",
    "OwnedFile",
    "PatchAssetRole",
    "PatchAudit",
    "PatchBundle",
    "PatchHealth",
    "PatchProfile",
    "PatchReceipt",
    "PatchTemplate",
    "CARTRIDGE_DOCUMENT_SCHEMA",
    "CARTRIDGE_INDEX_SCHEMA",
    "HUB_RELEASE_TAG",
    "INDEX_ASSET_NAME",
    "CartridgeDocument",
    "CartridgeIndex",
    "CartridgeIndexEntry",
    "UserSettings",
    "InstallPlan",
    "InstallReceipt",
    "game_relative_path",
    "normalize_game_relative_directory",
    "resolve_game_directory",
]
