"""Built-in publisher cartridges.

Disk cartridges under ``publisher-workspace/games`` remain the source of
truth. Built-ins are only used to seed an empty publisher workspace.
"""

from __future__ import annotations

from .models import PublisherCartridge


def create_builtin_cartridges() -> tuple[PublisherCartridge, ...]:
    return (
        PublisherCartridge(
            game_id="stellaris",
            display_name="群星 (Stellaris)",
            release_tag="stellaris",
            appinfo_name="stellaris_appinfo.json",
            steam_app_id="281990",
            dlc_relative_dir="dlc",
            patch_relative_dir=".",
            executable_relative_path="stellaris.exe",
            package_inspector="stellaris_zip",
        ),
        PublisherCartridge(
            game_id="civilization_6",
            display_name="文明6 (Civilization VI)",
            release_tag="civilization_6",
            appinfo_name="civilization_6_appinfo.json",
            steam_app_id="289070",
            dlc_relative_dir="DLC",
            patch_relative_dir="Base/Binaries/Win64Steam",
            dlc_archive_root_mode="strip_id_prefix",
            dlc_import_naming_mode="auto_prefix",
            dlc_import_layout_mode="children_if_root",
            executable_relative_path="Base/Binaries/Win64Steam/CivilizationVI.exe",
            package_inspector="directory",
            install_directory_from_slug=True,
        ),
        PublisherCartridge(
            game_id="hearts_of_iron_4",
            display_name="钢铁雄心4 (Hearts of Iron IV)",
            release_tag="hearts_of_iron_4",
            appinfo_name="hearts_of_iron_4_appinfo.json",
            steam_app_id="394360",
            dlc_relative_dir="dlc",
            patch_relative_dir=".",
            dlc_archive_root_mode="source",
            executable_relative_path="hoi4.exe",
            package_inspector="directory",
        ),
        PublisherCartridge(
            game_id="cities_skylines",
            display_name="都市天际线 (Cities: Skylines)",
            release_tag="cities_skylines",
            appinfo_name="cities_skylines_appinfo.json",
            steam_app_id="255710",
            dlc_relative_dir="Files",
            patch_relative_dir=".",
            dlc_archive_root_mode="strip_id_prefix",
            dlc_import_naming_mode="auto_prefix",
            dlc_import_layout_mode="grouped_leaf_paths",
            dlc_group_search_roots=("Radio",),
            executable_relative_path="Cities.exe",
            package_inspector="grouped_directory",
            install_directory_from_slug=False,
        ),
        PublisherCartridge(
            game_id="rimworld",
            display_name="边缘世界 (RimWorld)",
            release_tag="rimworld",
            appinfo_name="rimworld_appinfo.json",
            steam_app_id="294100",
            dlc_relative_dir="Data",
            patch_relative_dir="RimWorldWin64_Data/Plugins/x86_64",
            dlc_archive_root_mode="strip_id_prefix",
            dlc_import_naming_mode="auto_prefix",
            dlc_import_layout_mode="children_if_root",
            executable_relative_path="RimWorldWin64.exe",
            package_inspector="directory",
            install_directory_from_slug=True,
        ),
        PublisherCartridge(
            game_id="crusader_kings_3",
            display_name="十字军之王3 (Crusader Kings III)",
            release_tag="crusader_kings_3",
            appinfo_name="crusader_kings_3_appinfo.json",
            steam_app_id="1158310",
            dlc_relative_dir="game/dlc",
            patch_relative_dir="binaries",
            executable_relative_path="binaries/ck3.exe",
            package_inspector="directory",
        ),
        PublisherCartridge(
            game_id="victoria_3",
            display_name="维多利亚3 (Victoria 3)",
            release_tag="victoria_3",
            appinfo_name="victoria_3_appinfo.json",
            steam_app_id="529340",
            dlc_relative_dir="game/dlc",
            patch_relative_dir="binaries",
            executable_relative_path="binaries/victoria3.exe",
            package_inspector="directory",
        ),
        PublisherCartridge(
            game_id="workers_resources_soviet_republic",
            display_name="工人与资源：苏维埃共和国 (Workers & Resources: Soviet Republic)",
            release_tag="workers_resources_soviet_republic",
            appinfo_name="workers_resources_soviet_republic_appinfo.json",
            steam_app_id="784150",
            dlc_relative_dir="media_soviet/sounds",
            patch_relative_dir=".",
            dlc_archive_root_mode="strip_id_prefix",
            dlc_import_naming_mode="auto_prefix",
            dlc_import_layout_mode="children_if_root",
            executable_relative_path="SOVIET64.exe",
            package_inspector="directory",
            install_directory_from_slug=True,
        ),
        PublisherCartridge(
            game_id="civilization_7",
            display_name="文明7 (Sid Meier's Civilization VII)",
            release_tag="civilization_7",
            appinfo_name="civilization_7_appinfo.json",
            steam_app_id="1295660",
            dlc_relative_dir="DLC",
            patch_relative_dir="Base/Binaries/Win64",
            dlc_archive_root_mode="strip_id_prefix",
            dlc_import_naming_mode="auto_prefix",
            dlc_import_layout_mode="children_if_root",
            executable_relative_path="Base/Binaries/Win64/Civ7_Win64_DX12_FinalRelease.exe",
            package_inspector="directory",
            install_directory_from_slug=True,
        ),
        PublisherCartridge(
            game_id="age_of_wonders_4",
            display_name="奇迹时代4 (Age of Wonders 4)",
            release_tag="age_of_wonders_4",
            appinfo_name="age_of_wonders_4_appinfo.json",
            steam_app_id="1669000",
            dlc_relative_dir="Content",
            patch_relative_dir=".",
            dlc_archive_root_mode="strip_id_prefix",
            dlc_import_naming_mode="auto_prefix",
            dlc_import_layout_mode="children_if_root",
            executable_relative_path="AOW4.exe",
            package_inspector="directory",
            install_directory_from_slug=True,
        ),
    )


__all__ = ["create_builtin_cartridges"]
